### ISSUE TITLE
Runs out of memory on RTX 4090 with 24GB

### ISSUE THREAD

**Issue by yermandy** [henry123-boy/SpaTracker#14]
What are memory requirements? Cannot run on my RTX 4090 cards

**Comment by yermandy** [comment]
You say that `22GB GPU memory is sufficient`

> NVIDIA GPU (RTX A6000) with CUDA version 11.8. (Other GPUs are also suitable, and 22GB GPU memory is sufficient for dense tracking (~10k points) with our code.)

but it seems that it is not

**Comment by yermandy** [comment]
I used this command `python demo.py --model spatracker --downsample 1 --vid_name swing --len_track 0 --fps_vis 15  --fps 1 --grid_size 50 --gpu 2` with [this asset](https://zju3dv.github.io/SpaTracker/SpatialTracker_files/3d/swing.mp4)

**Comment by henry123-boy** [comment]
Hi, thank you for noticing our work and really appreciate for your feedback. I just checked the memory comsumption, finding that the `zoedepth` cause the OOM problem. Therefore, I just reduce the bach_size of mono depth estimation from `50` -> `30` (https://github.com/henry123-boy/SpaTracker/blob/main/models/spatracker/predictor.py#L173). And now It works for 24GB GPU. Or, actually you can separate the zoedepth away for handling extream long video.

**Comment by yermandy** [comment]
Thanks for the prompt answer. Unfortunately, it does not work on my data:

https://github.com/henry123-boy/SpaTracker/assets/39454881/9163fd1c-7cba-4613-a4c4-9237f32186d1

The same issue as you showed on the CoTracker example with a moving car: 

https://github.com/henry123-boy/SpaTracker/assets/39454881/e6916cca-1c32-4992-8287-2851955bca32

**Comment by henry123-boy** [comment]
Would you mind providing the video and the mask of target object in your data? Spatracker relies on the monocular depth estimation, and it seems a little bit challenging for acquiring the accurate depth.

**Comment by yermandy** [comment]
Yes, please

https://github.com/henry123-boy/SpaTracker/assets/39454881/8e2d03da-2529-46df-941d-501c95695e87

![video-short-2](https://github.com/henry123-boy/SpaTracker/assets/39454881/6ef20519-6938-439c-af50-f24807f73c62)

**Comment by yermandy** [comment]
I thought that the problem might be because of the underexposed video but the second one did not work also (besides the fact that I probably did not make a perfect mask):

https://github.com/henry123-boy/SpaTracker/assets/39454881/b7138847-d65c-49a9-8ea8-6dcb42d43871

**Comment by henry123-boy** [comment]
Hi andy! I  have tried the case you provided. But unfortunately, I find it is really challenging, and I guess the reason is that the video you provided is very close to grayscale image where the mouse and background are very similar. Meanwhile, in these cases, the monocular depth is not good. So the tracker is hard to work thereby.
