### ISSUE TITLE
How can I get dpt_beit_large_384.pt?

### ISSUE THREAD

**Issue by guanjunwu** [henry123-boy/SpaTracker#20]
Dear authors,
thanks for your great work!
I want to know from where can I download `dpt_beit_large_384.pt` easily ?
I tries many times to get the .pt files and found it time-comsuming, I'd appreciate if you can update step-by-step guidance on the `readme.md`

**Comment by guanjunwu** [comment]
ok I've successed reproduce the paper :)

**Comment by ricshaw** [comment]
where did you find the checkpoint?

**Comment by ricshaw** [comment]
nevermind, got the checkpoint and had to downgrade timm (pip install timm==0.6.7) to make it work

**Comment by suunnnnnj** [comment]
You can find in this link.

https://github.com/isl-org/MiDaS/releases/download/v3_1/dpt_beit_large_384.pt
