### ISSUE TITLE
Question regarding the implementation of `track_mask`

### ISSUE THREAD

**Issue by HalfSummer11** [henry123-boy/SpaTracker#24]
Hi Yuxi,

Thanks a lot for releasing the code and model for this great project! I was having problem understanding the implementation of `track_mask` here: https://github.com/henry123-boy/SpaTracker/blob/4e777d14852a83954e0f45a09791cc6888643f95/models/spatracker/models/core/spatracker/spatracker.py#L243-L244, where it looks like `track_mask` follows the original, unsorted point tracks. However, it is later used assuming the `N` dimension is sorted here: https://github.com/henry123-boy/SpaTracker/blob/4e777d14852a83954e0f45a09791cc6888643f95/models/spatracker/models/core/spatracker/spatracker.py#L701. I checked and didn't see any indexing by `sort_inds` in between as with other variables. Not sure if I'm missing something or it is a bug. It would be great if you could look into it. Many thanks!

**Comment by henry123-boy** [comment]
Hi Yijia,

Thank you for careful review of our codes. I think you are right. In https://github.com/henry123-boy/SpaTracker/blob/4e777d14852a83954e0f45a09791cc6888643f95/models/spatracker/models/core/spatracker/spatracker.py#L243, `first_positive_inds` should be replaced with `first_positive_sorted_inds`.  I apologize for the bugs, cause this code has been re-encapsulated before releasing (probably bugs happen at that time).  I will fix it, or would you mind pushing a commit? Really appreciate your contribution.

Best,
yuxi

**Comment by HalfSummer11** [comment]
Thanks a lot for your reply, Yuxi!
