### ISSUE TITLE
release of code and checkpoints

### ISSUE THREAD

**Issue by hanxuel** [henry123-boy/SpaTracker#3]
Awesome work. When will you release the code and checkpoints?

**Comment by henry123-boy** [comment]
Thank you for noticing our work!🥰 And codes and checkpoints are planned to release in the late April, let's see.

**Comment by henry123-boy** [comment]
Thank you for noticing our work!🥰 And codes and checkpoints are planned to release in the late April, let's see.

**Comment by bhack** [comment]
Any update?
