### ISSUE TITLE
Question about the pred_tracks units and ranges

### ISSUE THREAD

**Issue by skygoo2000** [henry123-boy/SpaTracker#32]
Hi! Yuxi,

Thanks a lot for releasing the code and model for this awesome project! I learned a lot from this code.
However, I am still a little confused about the `pred_tracks`, especially for the range. I found that there is a huge discrepancy in z-values between different samples.
I will be grateful if you can point out the range and units of the `pred_tracks `z -z-values (just like x and y)

**Comment by henry123-boy** [comment]
Hi, thank you for your questioning. We use the metric depth estimator, `ZoeDepth`, where the z-values are aligned with the metric depth (meters). Meanwhile, we truncate the depth range within 0-65 meters, so the furthest distance will be smaller than 65 meters.
Hope this could help!
