### ISSUE TITLE
Real live video and license

### ISSUE THREAD

**Issue by JVal123** [henry123-boy/SpaTracker#4]
Hello! I have a question regarding the functionality of the Spatial Tracker.

Will this work on real live video, for example video being streamed from an AR system like the hololens2? Or will it only work on pre-recorded videos?

What will be the license for the code?

**Comment by bhack** [comment]
I have the same question is the a license file?

**Comment by bhack** [comment]
@cherubicXN Can you add a license file in the repo?

**Comment by cherubicXN** [comment]
Hi @bhack, thanks for your reminder. I have added the license by following [CoTracker](https://github.com/facebookresearch/co-tracker?tab=License-1-ov-file).

**Comment by bhack** [comment]
Ok thanks but in in this way it is not going to be an alternative to CoTracker for many users at least up until they are going to finally re-licensing it like it was done for Dinov2. See https://github.com/facebookresearch/co-tracker/issues/31 for more details.
Probably the new 2d SOTA [bootstap](https://github.com/google-deepmind/tapnet) has a more permissive licensing in the meantime but I don't know really your team constrains about what kind of license to adopt.

**Comment by bhack** [comment]
So are you going to confirm Creative commons Attribution-NonCommercial ?
