### ISSUE TITLE
configuration issue of pip install flash-attn --no-build-isolation

### ISSUE THREAD

**Issue by YuanZi1501040205** [henry123-boy/SpaTracker#7]
pip install flash-attn --no-build-isolation
Collecting flash-attn
  Using cached flash_attn-2.5.8.tar.gz (2.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-cd4z2pwx/flash-attn_bcfcf6f3aeee45fe85c321fa64f3f0c8/setup.py", line 9, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by henry123-boy** [comment]
Hi, thank you for trying our model. In our new update, installation of `flash-attn` is not neccessary if your `torch__version` is > 2.2.0, where the `flash-attn` has been encapsulated.
